routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/',[FrontendController::class, 'index'])->name('frontend.index');

require __DIR__.'/auth.php';

Route::middleware('auth')->group(function(){

Route::controller(CategoryController::class)->group(function() {
    Route::prefix('categories')->name('categories.')->group(function() {
        Route::get('/pdf', 'downloadPdf')->name('pdf');
        Route::get('/excel', 'downloadExcel')->name('excel');

        // Soft delete
        Route::get('/trash', 'trash')->name('trash');
        Route::get('/trash/{id}/view', 'trashedShow')->name('trash.show');
        Route::get('/{id}/restore', 'restore')->name('restore');
        Route::delete('/{id}/delete', 'delete')->name('delete');
    });
});
Route::resource('categories', CategoryController::class);

Route::controller(ProductController::class)->group(function() {
    Route::prefix('products')->name('products.')->group(function() {
        Route::get('/pdf', 'downloadPdf')->name('pdf');
        Route::get('/excel', 'downloadExcel')->name('excel');

        Route::get('/pdf-trashed', 'downloadTrashedPdf')->name('pdf.trashed');
        Route::get('/excel-trashed', 'downloadTrashedExcel')->name('excel.trashed');

        // Soft delete
        Route::get('/trash', 'trash')->name('trash');
        Route::get('/trash/{id}/view', 'trashedShow')->name('trash.show');
        Route::get('/{id}/restore', 'restore')->name('restore');
        Route::delete('/{id}/delete', 'delete')->name('delete');
    });
});
Route::resource('products', ProductController::class);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Image;
use Barryvdh\DomPDF\Facade\Pdf;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('backend.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $requestData = [
            'name'=>$request->name,
            'is_active'=>$request->is_active ? true:false,
            'image' => $this->uploadImage($request->file('image'))

        ];
        Category::create($requestData);
        return redirect()
        ->route('categories.index')
        ->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('backend.categories.show',compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('backend.categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request,Category $category)
    {
        $requestData = [
            'name'=>$request->name,
            'is_active'=>$request->is_active ? true:false,
            // 'image'=>$imgFileName
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));
        }

        $category->update($requestData);
        // Category::Create($requestData);
        return redirect()
        ->route('categories.index')
        ->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()
        ->route('categories.index')
        ->withMessage('Successfully Deleted');
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('Y-m-d') . time() . $originalName;

        // $image->move(storage_path('/app/public/categories'), $fileName);

        Image::make($image)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/categories/' . $fileName);

        return $fileName;
    }

    public function trash()
    {
        $categories = Category::onlyTrashed ()->get();
        return view('backend.categories.trash',compact('categories'));
    }

    public function delete($id)
    {
        $category = Category::onlyTrashed()->find($id);
        $category->forceDelete();
        return redirect()
        ->route('categories.trash')
        ->withMessage('Successfully Deleted');
        // return view('backend.categories.trash',compact('categories'));
    }
    public function restore($id)
    {
        $category = Category::onlyTrashed()->find($id);
        $category->restore();
        return redirect()
        ->route('categories.trash')
        ->withMessage('Successfully Restore');
    }

    public function downloadPdf()
    {
        $categories = Category::all();
        $pdf = Pdf::loadView('backend.categories.pdf', compact('categories'));
        return $pdf->download('category-list.pdf');
    }
}

resources/views/backend/categories/create.blade.php
<x-backend.master>
    <x-slot:title>
        Category Create
        </x-slot>
        <main id="main" class="main">
            @if (session('message'))
                <span class="text-success">{{ session('message') }}</span>
            @endif

            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Categories</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                    <a href="{{ route('categories.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">
                            <span data-feather="list"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>

            <x-forms.errors />

            <form action="{{ route('categories.store') }}" method="post" enctype="multipart/form-data">

                @csrf

                <x-forms.input type="text" name="name" placeholder="Enter Name" required
                    label="Categories Name" />

                <x-forms.input type="file" name="image" label='Picture' />

                @php
                    $checklist = ['Is Active'];
                @endphp

                <x-forms.checkbox name="is_active" id="is_active" :checklist="$checklist" />

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

        </main>




</x-backend.master>

resources/views/backend/categories/edit.blade.php
<x-backend.master>
    <x-slot:title>
        Category Update
        </x-slot>
        <main id="main" class="main">
            {{-- sir ar theke uporer part ta  --}}
            <div
                class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Categories</h1>
                <div class="btn-group me-2">
                    {{-- class="btn-toolbar mb-2 mb-md-0" --}}

                    <a href="{{ route('categories.index') }}">
                        <button type="button" class="btn btn-sm btn-outline-info">
                            <span data-feather="List"></span>
                            List
                        </button>
                    </a>
                </div>
            </div>

            {{-- validation Check message --}}
            <x-forms.errors />

            {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif --}}
            {{-- Form dite hobe --}}
            <form action="{{ route('categories.update', $category->id) }} " method="post" enctype="multipart/form-data">
                @csrf
                @method('patch')
                <x-forms.input type="text" name="name" :value="old('name', $category->name)" placeholder="Enter Category Name"
                    required />
                {{-- <div class="mb-3">
                    <label for="nameInput" class="form-label ">Name</label>
                    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                        id="exampleInputEmail1" value="{{ $category->name }} ">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div> --}}

                <img src="{{ asset('storage/categories/' . $category->image) }}" height="250" />

                <x-forms.input type="file" name="image" label='Picture' />

                @php
                    $checklist = [
                    "Is_Active"=> 'is_active'
                  ];

                    if ($category->is_active) {
                        $checkedItems = [0];
                    } else {
                        $checkedItems = [];
                    }
                @endphp

                <x-forms.checkbox :checklist="$checklist" :checkedItems="$checkedItems" name="is_active" />

                <button type="submit" class="btn btn-primary">Submit</button>

                {{-- <input type="file" name="image" id="image">

                <div class="mb-3 form-check">
                    <input name="is_active" type="checkbox" class="form-check-input" id="exampleCheck1"
                        @if ($category->is_active) checked @endif>
                    <label class="form-check-label" for="isActiveInput">Is Active ?</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button> --}}
            </form>
        </main>




</x-backend.master>

resources/views/backend/categories/index.blade.php
<x-backend.master>
    <x-slot:title>
        Categoiries List
    </x-slot:title>

    <main id="main" class="main">

        <x-forms.message />

        {{-- @if (session('message'))
            <span class="text-success">{{ session('message') }} </span>
        @endif --}}

        {{-- sir ar theke uporer part ta  --}}
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <div class="btn-group me-2">
                    <a href="{{ route('categories.pdf') }}">
                        <button type="button" class="btn btn-sm btn-outline-success">PDF</button>
                    </a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Excel</button>
                    <a href="{{ route('categories.trash') }}">
                        <button type="button" class="btn btn-sm btn-outline-danger">Trash</button>
                    </a>
                </div>
                <a href="{{ route('categories.create') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        Add New
                    </button>
                </a>
            </div>
        </div>

        {{-- <a href="{{ route('categories.create') }} ">Create</a> --}}
        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Category Name </th>
                    <th>Action</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }} </td>
                        <td>{{ $category->name }} </td>
                        <td>
                            <a class="btn btn-success" href="{{ route('categories.show', $category->id) }} ">Show
                            </a> |
                            <a class="btn btn-warning" href="{{ route('categories.edit', $category->id) }} ">Edit</a> |
                            <form action="{{ route('categories.destroy', $category->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" href=""
                                    onclick="return confirm('Are You Sure?')">Delete</button>
                            </form>

                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </main>
</x-backend.master>

resources/views/backend/categories/pdf.blade.php
<table class="table">
    <thead>
        <tr>
            <th>SL#</th>
            <th>Category Name </th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach ($categories as $category)
            <tr>
                <td>{{ $loop->iteration }} </td>
                <td>{{ $category->name }} </td>
            </tr>
        @endforeach

    </tbody>
</table>
<

resources/views/backend/categories/show.blade.php
<x-backend.master>
    <x-slot:title>
        Show Categories
    </x-slot:title>
    <main id="main" class="main">


        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="list"></span>
                        List
                    </button>
                </a>
            </div>
        </div>

        <h1>Title: {{ $category->name }}</h1>

        <img src="{{ asset('storage/categories/' . $category->image) }}" />

        <p>Is Active ?: {{ $category->is_active ? 'Yes' : 'No' }}</p>
{{--
        <h1>Products</h1>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>SL#</th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($category->products as $product)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $product->title }}</td>
                    </tr>
                @endforeach
            </tbody> --}}
        </table>

    </main>
</x-backend.master>

resources/views/backend/categories/trash.blade.php
<x-backend.master>
    <x-slot:title>
        {{ __('Trash') }}
    </x-slot:title>

    <main id="main" class="main">
        <x-forms.message />
        {{-- @if (session('message'))
            <span class="text-success">{{ session('message') }} </span>
        @endif --}}

        {{-- sir ar theke uporer part ta  --}}
        <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Categories</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
                <a href="{{ route('categories.index') }}">
                    <button type="button" class="btn btn-sm btn-outline-primary">
                        <span data-feather="plus"></span>
                        {{ __('List') }}
                    </button>
                </a>
            </div>
        </div>

        {{-- <a href="{{ route('categories.create') }} ">Create</a> --}}
        <table class="table">
            <thead>
                <tr>
                    <th>{{ __('SL#') }}</th>
                    <th>{{ __('Category Name') }}</th>
                    <th>{{ __('Action') }}</th>
                </tr>
            </thead>

            <tbody>

                @foreach ($categories as $category)
                    <tr>
                        <td>{{ $loop->iteration }} </td>
                        <td>{{ $category->name }} </td>
                        <td>
                            <a class="btn btn-success" href="{{ route('categories.show', $category->id) }} ">Show
                            </a> |

                            <a class="btn btn-warning"
                                href="{{ route('categories.restore', $category->id) }} ">Restore</a> |

                            <form action="{{ route('categories.delete', $category->id) }}" method="post"
                                style="display:inline">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" href=""
                                    onclick="return confirm('File will be permanently deleted')">Delete</button>
                            </form>

                        </td>
                    </tr>
                @endforeach

            </tbody>
        </table>
    </main>
</x-backend.master>